apiVersion: v1
kind: Service
metadata:
  name: idgenerator
spec:
  ports:
  - name: 8080-8080-tcp
    nodePort: 31180
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: idgenerator
  sessionAffinity: None
  type: NodePort
