apiVersion: v1
kind: Service
metadata:
  name: idgenerator
spec:
  ports:
  - name: 80-80-tcp
    nodePort: 31180
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: idgenerator
  sessionAffinity: None
  type: NodePort
